### ISSUE TITLE
Emerald theme for dark Glare-cupertino

### ISSUE THREAD

**Issue by ChemBioScripting** [sixsixfive/Glare#3]
Hello, I hope it's the right way to communicate here (I have not much practice with GitHub).

I tested your dark Glare-cupertino theme for my XFCE desktop, and I really enjoyed it, combined with another gtk-theme and some icons. Then has been born also the idea to install Compiz, and so I noticed the lack of an Emerald version, so I thought I would try to create it by myself: http://compiz-themes.org/content/show.php/GRV-Glare-Dark-Cupertino?content=170508

Here my GitHub repository:
https://github.com/ChemBioScripting/GRV-Glare-Dark-Cupertino

I wanted to share it and tell you this, if maybe you want to integrate an Emerald version too, that would be a nice idea, I think :-). Greetings,

Riccardo

**Comment by sixsixfive** [comment]
thx i will see if i can use it but isn't compiz not abandoned since years?

**Comment by ChemBioScripting** [comment]
Hi, thanks for your reply. I really don't know this news: I installed Compiz just few days ago on Fedora XFCE without any problem, so packages are available... Do you know a newest project which replaces it?

**Comment by sixsixfive** [comment]
> Do you know a newest project which replaces it? 
Afaik only KDEs Kwin has all those wobby windows/desktop cube stuff today, but the most windowmanagers have now support for shadows & transparency others like openbox can use compton

**Comment by ChemBioScripting** [comment]
Thank you for informations!
If you feel like, you can close this item: I wanted to let you know the presence of this version, and the intent is now managed :-)

Greetings and thank you,
Riccardo
